version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
