version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  channels_worker:
    build:
      context: .
    restart: always
    command: python manage.py runworker
    depends_on:
      - redis
    volumes:
      - ./:/app

  backend:
    build:
      context: .
    restart: always
    command: daphne -b 0.0.0.0 -p 8001 RealChat.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./:/app

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
  redis_data:
